#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from typing import Any

from relay_consumer import parse_frontmatter_md
from relay_store import TelegramRelayStore, atomic_write_text, iso_z, sanitize_text


def parse_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def ensure_repo_relative_target(repo_root: Path, target: str) -> Path:
    target_path = (repo_root / target).resolve()
    repo_root_resolved = repo_root.resolve()
    if repo_root_resolved not in [target_path, *target_path.parents]:
        raise ValueError(f"publish_target_path escapes repo root: {target}")
    return target_path


def render_publish_markdown(*, fm: dict[str, Any], body: str, source_artifact: Path) -> str:
    trace_id = str(fm.get("trace_id", ""))
    impl_id = str(fm.get("impl_id", ""))
    intent = str(fm.get("intent", ""))
    source = str(fm.get("source", ""))
    response = body.strip()
    if response.startswith("## Response"):
        response = response[len("## Response") :].lstrip()
    lines = [
        "---",
        f"generated_by: telegram-relay-publisher",
        f"generated_at: {iso_z()}",
        f"trace_id: {trace_id}",
        f"implementation: {impl_id}",
        f"intent: {intent}",
        f"source_artifact: {source_artifact}",
        f"relay_source: {source}",
        "---",
        "",
        "# Relay Update",
        "",
        f"- Implementation: `{impl_id}`",
        f"- Trace ID: `{trace_id}`",
        f"- Intent: `{intent}`",
        f"- Source artifact: `{source_artifact}`",
        "",
        "## Response",
        sanitize_text(response),
        "",
        "## Publish Notes",
        "- Generated by explicit publisher step.",
        "- No direct Telegram-to-repo mutation occurred.",
        "",
    ]
    return "\n".join(lines)


def maybe_git_commit(repo_root: Path, target_path: Path, message: str) -> None:
    subprocess.run(["git", "-C", str(repo_root), "add", str(target_path)], check=True)
    subprocess.run(["git", "-C", str(repo_root), "commit", "-m", message], check=True)


def publish_one(store: TelegramRelayStore, artifact_path: Path, *, commit: bool = False) -> tuple[str, str]:
    fm, body = parse_frontmatter_md(artifact_path)
    requested = parse_bool(fm.get("publish_to_github_requested"))
    approved = parse_bool(fm.get("publish_to_github_approved"))
    target = str(fm.get("publish_target_path", "")).strip()
    trace_id = str(fm.get("trace_id", ""))
    intent = str(fm.get("intent", "unknown"))

    if not requested:
        return ("skipped", "publish_to_github_requested is false")
    if not approved:
        return ("blocked", "publish_to_github_approved is false")
    if not target:
        return ("failed", "publish_target_path is empty")

    # .../fde/implementations/<impl-id>/telegram -> repo root is parents[2] (= .../fde)
    repo_root = Path(store.paths.base).parents[2]
    target_path = ensure_repo_relative_target(repo_root, target)
    target_path.parent.mkdir(parents=True, exist_ok=True)

    content = render_publish_markdown(fm=fm, body=body, source_artifact=artifact_path)
    atomic_write_text(target_path, content)

    store.append_event(
        {
            "trace_id": trace_id or store.new_trace_id("publish"),
            "source": "relay-publisher",
            "direction": "internal",
            "status": "published",
            "intent": intent,
            "artifact_path": str(artifact_path),
            "publish_target_path": str(target_path),
            "provenance": "relay-publisher",
        }
    )

    commit_msg = str(fm.get("publish_commit_message", "")).strip() or f"relay: publish {target_path.relative_to(repo_root)}"
    if commit:
        maybe_git_commit(repo_root, target_path, commit_msg)
        store.append_event(
            {
                "trace_id": trace_id or store.new_trace_id("publish"),
                "source": "relay-publisher",
                "direction": "internal",
                "status": "git_committed",
                "artifact_path": str(artifact_path),
                "publish_target_path": str(target_path),
                "git_commit_message": commit_msg,
                "provenance": "relay-publisher",
            }
        )

    return ("published", str(target_path))


def main() -> int:
    parser = argparse.ArgumentParser(description="Explicit publisher for approved Telegram relay artifacts")
    parser.add_argument("--impl-id", required=True, help="Implementation id under implementations/")
    parser.add_argument(
        "--implementations-root",
        default="/home/mical/fde/implementations",
        help="Implementations root path",
    )
    parser.add_argument(
        "--from-dir",
        choices=["outbox", "archive-processed"],
        default="outbox",
        help="Read candidate artifacts from outbox or archive/processed",
    )
    parser.add_argument("--artifact", help="Specific artifact path to publish")
    parser.add_argument("--once", action="store_true", help="Process available artifacts and exit")
    parser.add_argument("--commit", action="store_true", help="Commit published file(s) to git (explicit)")
    args = parser.parse_args()

    store = TelegramRelayStore(args.implementations_root, args.impl_id)
    store.ensure_layout()

    if args.artifact:
        candidates = [Path(args.artifact)]
    elif args.from_dir == "outbox":
        candidates = sorted(store.paths.outbox.glob("*.md"))
    else:
        candidates = sorted((store.paths.archive / "processed").glob("*.md"))

    if not candidates:
        print("No candidate artifacts found.")
        return 0

    for path in candidates:
        status, detail = publish_one(store, path, commit=args.commit)
        print(f"{path.name}: {status} -> {detail}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
